In [1]:
import os

In [3]:
fromfile = './data/aiwar_train_data'
todir = './data_split/'
absfrom, absto = map(os.path.abspath, [fromfile, todir])
print('Splitting', absfrom, 'to', absto)

Splitting /Users/hushiwei/PycharmProjects/PythonDataAnalysis/learnOthers/data/aiwar_train_data to /Users/hushiwei/PycharmProjects/PythonDataAnalysis/learnOthers/data_split


In [14]:
path="/Users/hushiwei/PycharmProjects/ApplistPredictGender/data_split"
os.listdir(path)[0:1]

['青海']

In [6]:
import random


In [7]:
random.sample([1,2,34,4],3)

[4, 2, 34]

In [15]:
apps=[15, 30, 28, 29]

In [17]:
for x,item in enumerate(apps):
    print(str(x)+" : "+str(item))

0 : 15
1 : 30
2 : 28
3 : 29


In [11]:
 list(filter(lambda x: x not in [15, 30, 28, 29], apps))

[]

In [27]:
arr=[218, 63, 53, 113, 134, 68, 170, 26, 22, 49, 28, 29, 347, 218,360, 585, 307, 70, 78, 15, 55, 18, 30, 51, 35, 116]

In [30]:
set_all={}
for key in arr:
    v=set_all.get(key,0)
    set_all[key]=(v+1)
print(set_all)

{218: 2, 63: 1, 53: 1, 113: 1, 134: 1, 68: 1, 170: 1, 26: 1, 22: 1, 49: 1, 28: 1, 29: 1, 347: 1, 360: 1, 585: 1, 307: 1, 70: 1, 78: 1, 15: 1, 55: 1, 18: 1, 30: 1, 51: 1, 35: 1, 116: 1}


In [31]:
set_all=dict((k,v) for k,v in set_all.items() if v>1)
print(set_all)

{218: 2}


In [32]:
import numpy as np

In [35]:
np.zeros((2,3),dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
from sklearn.cross_validation import StratifiedShuffleSplit

/Users/hushiwei/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [77]:
X=np.array([
    [1,2],
    [3,4],
    [1,2],
    [3,4],
    [7,8],
    [9,10]
])
y = np.array([0, 0, 1, 1,0,0])
sss = StratifiedShuffleSplit(y, 1, test_size=0.2, random_state=0)
len(sss)

1

In [78]:
print(sss)

StratifiedShuffleSplit(labels=[0 0 1 1 0 0], n_iter=1, test_size=0.2, random_state=0)


In [79]:
for train_index,test_index in sss:
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)

TRAIN: [4 1 5 2] TEST: [0 3]
[[ 7  8]
 [ 3  4]
 [ 9 10]
 [ 1  2]]


In [81]:
X[[1,3]]

array([[3, 4],
       [3, 4]])

In [85]:
a=dict()
a["bayes"]=(lambda x,y:x*y,"haha")
a["hu"]=(lambda x,y:x+y,"lalalal")

a["bayes"][0](3,5)

15

In [89]:
a["bayes"][1]

'haha'

In [96]:
a=np.random.randint(5, size=(6, 100))
a

array([[0, 2, 0, 0, 2, 3, 3, 4, 4, 1, 1, 1, 4, 0, 4, 0, 1, 2, 4, 1, 4, 0,
        0, 4, 4, 2, 0, 0, 0, 4, 4, 3, 4, 2, 1, 0, 3, 1, 1, 0, 0, 3, 0, 2,
        1, 1, 1, 1, 3, 4, 3, 2, 0, 0, 3, 0, 2, 3, 0, 0, 1, 4, 4, 4, 3, 1,
        3, 3, 2, 3, 0, 2, 4, 4, 0, 3, 1, 4, 0, 1, 4, 3, 0, 3, 4, 3, 4, 4,
        0, 0, 4, 4, 2, 0, 3, 3, 2, 3, 0, 4],
       [1, 1, 3, 1, 2, 1, 2, 4, 4, 0, 2, 2, 2, 0, 2, 4, 3, 1, 3, 0, 3, 0,
        3, 4, 0, 2, 0, 3, 0, 2, 4, 2, 2, 0, 3, 0, 4, 4, 1, 2, 4, 0, 4, 1,
        3, 0, 3, 1, 2, 1, 4, 0, 0, 3, 1, 4, 2, 3, 3, 0, 1, 3, 3, 3, 0, 2,
        1, 2, 3, 3, 2, 3, 2, 0, 2, 2, 0, 2, 4, 3, 2, 0, 2, 0, 1, 1, 1, 0,
        4, 4, 0, 3, 2, 0, 0, 3, 2, 2, 4, 0],
       [2, 0, 2, 2, 0, 1, 0, 2, 3, 2, 1, 4, 2, 0, 4, 3, 3, 4, 4, 2, 2, 0,
        1, 4, 2, 4, 1, 4, 3, 1, 1, 1, 1, 1, 0, 4, 4, 2, 0, 2, 1, 3, 1, 3,
        2, 4, 3, 2, 4, 2, 2, 2, 0, 2, 2, 4, 0, 2, 0, 1, 2, 4, 3, 3, 3, 4,
        1, 3, 4, 2, 2, 3, 2, 4, 0, 2, 4, 1, 3, 4, 3, 2, 2, 4, 1, 4, 0, 0,
        2, 0, 3, 1, 0,

In [95]:
a[2:3]

array([[2, 1, 3, 2, 2, 3, 3, 0, 1, 4, 2, 1, 0, 3, 2, 0, 0, 4, 0, 2, 1, 4,
        2, 3, 3, 2, 4, 3, 2, 2, 4, 2, 0, 4, 3, 2, 2, 4, 0, 2, 4, 3, 1, 1,
        4, 4, 3, 1, 2, 3, 0, 0, 2, 1, 1, 2, 1, 2, 4, 0, 2, 3, 3, 3, 4, 1,
        4, 2, 4, 4, 0, 2, 3, 0, 4, 4, 2, 3, 1, 3, 4, 0, 0, 4, 3, 1, 2, 3,
        3, 1, 1, 3, 0, 1, 2, 0, 2, 3, 4, 3]])

In [104]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
print(clf.predict(X[2:3]))
clf.score(X[5:6],[6])

[3]


1.0

In [107]:
from sklearn.metrics import classification_report
target_names = set(['0', '1'])
arr=np.array([6])
print(classification_report([6],arr,target_names))

TypeError: iteration over a 0-d array

In [1]:
arr=['a','b','c','d']

In [3]:
arr.index('d')

3

In [4]:
import numpy as np

In [5]:
mat=np.zeros((2,3))
mat

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
mat[1,2]=1
mat

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  1.]])