In [1]:
from sklearn import datasets

In [2]:
diabetes=datasets.load_diabetes()

In [5]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [6]:
y=diabetes.target
x=diabetes.data

In [7]:
x.shape

(442, 10)

In [8]:
x[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [9]:
y[:10]

array([ 151.,   75.,  141.,  206.,  135.,   97.,  138.,   63.,  110.,  310.])

In [10]:
type(diabetes)

sklearn.utils.Bunch

In [11]:
feature_names=['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [12]:
from sklearn.linear_model import Lasso
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import GridSearchCV

We will split our data into separate test and train sets of data (train is used to train the model and test is used for model performance testing and evaluation).

In [16]:
diabetes=datasets.load_diabetes()
x_train=diabetes.data[:310]
y_train=diabetes.target[:310]

x_test=diabetes.data[310:]
y_test=diabetes.target[310:]

Then we will define the model we want to use and the parameter space for one of the model’s hyperparameters. Here we will search the parameter alpha of the Lasso model. This parameter basically controls the strictness our regularization.


In [15]:
lasso=Lasso(random_state=0)
alpha=np.logspace(-4,-0.5,30)
alpha

array([  1.00000000e-04,   1.32035178e-04,   1.74332882e-04,
         2.30180731e-04,   3.03919538e-04,   4.01280703e-04,
         5.29831691e-04,   6.99564216e-04,   9.23670857e-04,
         1.21957046e-03,   1.61026203e-03,   2.12611233e-03,
         2.80721620e-03,   3.70651291e-03,   4.89390092e-03,
         6.46167079e-03,   8.53167852e-03,   1.12648169e-02,
         1.48735211e-02,   1.96382800e-02,   2.59294380e-02,
         3.42359796e-02,   4.52035366e-02,   5.96845700e-02,
         7.88046282e-02,   1.04049831e-01,   1.37382380e-01,
         1.81393069e-01,   2.39502662e-01,   3.16227766e-01])

Then we will initialize an estimator that will identify the model to be used. Here we notice that the process is identical for both learning a single model and a grid search of models, i.e. they both are objects of the estimator class.

In [17]:
estimator=GridSearchCV(lasso,dict(alpha=alpha))
estimator.fit(x_train,y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': array([  1.00000e-04,   1.32035e-04,   1.74333e-04,   2.30181e-04,
         3.03920e-04,   4.01281e-04,   5.29832e-04,   6.99564e-04,
         9.23671e-04,   1.21957e-03,   1.61026e-03,   2.12611e-03,
         2.80722e-03,   3.70651e-03,   4.89390e-03,   6.46167e-03,
         8....    7.88046e-02,   1.04050e-01,   1.37382e-01,   1.81393e-01,
         2.39503e-01,   3.16228e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [18]:
estimator.best_score_

0.46540637590235312

In [19]:
estimator.best_estimator_

Lasso(alpha=0.025929437974046669, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [20]:
estimator.predict(x_test)

array([ 203.42104984,  177.6595529 ,  122.62188598,  212.81136958,
        173.61633075,  114.76145025,  202.36033584,  171.70767813,
        164.28694562,  191.29091477,  191.41279009,  288.2772433 ,
        296.47009002,  234.53378413,  210.61427168,  228.62812055,
        156.74489991,  225.08834492,  191.75874632,  102.81600989,
        172.373221  ,  111.20843429,  290.22242876,  178.64605207,
         78.13722832,   86.35832297,  256.41378529,  165.99622543,
        121.29260976,  153.48718848,  163.09835143,  180.0932902 ,
        161.4330553 ,  155.80211635,  143.70181085,  126.13753819,
        181.06471818,  105.03679977,  131.0479936 ,   90.50606427,
        252.66486639,   84.84786067,   59.41005358,  184.51368208,
        201.46598714,  129.96333913,   90.65641478,  200.10932516,
         55.2884802 ,  171.60459062,  195.40750666,  122.14139787,
        231.72783897,  159.49750022,  160.32104862,  165.53701866,
        260.73217736,  259.77213787,  204.69526082,  185.66480