numpy 学习笔记

In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)

In [11]:
my_list=list(range(1000000))

# numpy和普通数组的效率比较

In [12]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 11.9 ms, sys: 4.54 ms, total: 16.4 ms
Wall time: 14.4 ms


In [13]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 744 ms, sys: 183 ms, total: 927 ms
Wall time: 927 ms


很明显,numpy的效率要高很多

#  The NumPy ndarray: A Multidimensional Array Object

In [14]:
# 构造几个数据
data=np.random.randn(2,3)
data

array([[-0.58719729, -0.59255458, -1.86551378],
       [ 1.40452623,  0.61605647,  0.49629843]])

In [15]:
data*10

array([[ -5.87197293,  -5.9255458 , -18.65513776],
       [ 14.04526231,   6.1605647 ,   4.9629843 ]])

In [16]:
data+data

array([[-1.17439459, -1.18510916, -3.73102755],
       [ 2.80905246,  1.23211294,  0.99259686]])